
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: item_cart_development

test:
  <<: *default
  database: item_cart_test

production:
  <<: *default
  database: myapp_production
  username: item_cart
  password: <%= ENV['ITEM_CART_DATABASE_PASSWORD'] %>
